# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
      ./hardware.nix
      ./home-julien.nix
    ];

  luj.mediaserver.enable = true;
  luj.homepage.enable = true;
  luj.drone = {
    enable = true;
    nginx = {
      enable = true;
      subdomain = "ci";
    };
  };
 
  nix.maxJobs = lib.mkDefault 8;

  networking.hostName = "lisa"; # Define your hostname.
  networking.interfaces.ens18.useDHCP = true;
  networking.interfaces.ens19.useDHCP = false;
  networking.interfaces.ens19.ipv6.addresses = [{
    address = "2a01:e0a:5f9:9681:5880:c9ff:fe9f:3dfb";
    prefixLength = 120;
  }];
  networking.firewall.allowedTCPPorts = [ 22 80 443 8096 8920 ];
  networking.firewall.allowedUDPPorts = [ 22 80 443 1900 7359 ];
  networking.firewall.allowedUDPPortRanges = [{ from = 60000; to = 61000; }];

  system.stateVersion = "20.09"; # Did you read the comment?

}
