{
  pkgs,
  config,
  lib,
  ...
}:
let
  cfg = config.luj.emails.mujmap;

  accounts = {
    malka = {
      principal = "malka";
      secretName = "work-mail-pw";
    };
    ens = {
      principal = "julien-ens";
      secretName = "julien-mirrors-stalwart-pw";
    };
    tp = {
      principal = "julien-tp";
      secretName = "julien-mirrors-stalwart-pw";
    };
    dgnum = {
      principal = "julien-dgnum";
      secretName = "julien-mirrors-stalwart-pw";
    };
  };

  mkTomlText = _: a: ''
    # Generated by home-manager-modules/mails/mujmap.nix. Do not edit by hand.
    #
    session_url = "https://mail.luj.fr/.well-known/jmap"

    username = "${a.principal}"
    password_command = "cat ${config.age.secrets.${a.secretName}.path}"

    concurrent_downloads = 8

    timeout = 60

    [tags]
    inbox = "inbox"
    sent = "sent"
    deleted = "deleted"
    spam = "spam"
    important = "important"
    phishing = "phishing"
  '';

  syncScript = pkgs.writeShellScript "mujmap-sync-all" ''
    set -u
    any_ok=0
    last_rc=0
    for acct in ${lib.concatStringsSep " " (lib.attrNames accounts)}; do
      echo "=== $acct ==="
      if ${pkgs.mujmap-patched}/bin/mujmap -C "$HOME/Maildir/$acct" sync; then
        any_ok=1
      else
        last_rc=$?
        echo "mujmap sync failed for $acct (exit $last_rc)"
      fi
    done
    if [ $any_ok -eq 0 ]; then
      exit $last_rc
    fi
    exit 0
  '';
in
{
  options.luj.emails.mujmap = {
    enable = lib.mkEnableOption "mujmap-based JMAP sync";
  };

  config = lib.mkIf cfg.enable {
    age.secrets.julien-mirrors-stalwart-pw = {
      file = ../../machines/akhaten/julien-mirrors-stalwart-pw.age;
    };

    home.packages = [
      pkgs.mujmap-patched
      pkgs.notmuch
    ];

    home.file = lib.mapAttrs' (
      acct: a:
      lib.nameValuePair "Maildir/${acct}/mujmap.toml" {
        text = mkTomlText acct a;
      }
    ) accounts;

    systemd.user.services.mujmap-sync = {
      Unit = {
        Description = "mujmap sync for all 4 Stalwart principals";
        After = [ "network-online.target" ];
        Wants = [ "network-online.target" ];
      };
      Service = {
        Type = "oneshot";
        ExecStart = "${syncScript}";
      };
    };

    systemd.user.timers.mujmap-sync = {
      Unit.Description = "Periodic mujmap sync for all 4 Stalwart principals";
      Timer = {
        OnBootSec = "1min";
        OnUnitActiveSec = "1min";
        RandomizedDelaySec = "10s";
        Persistent = true;
      };
      Install.WantedBy = [ "timers.target" ];
    };

    home.activation.makeMaildirDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      run mkdir -p $HOME/Maildir/{malka,ens,tp,dgnum}
    '';
  };
}
