keys:
  - &macintosh age1caua5n9k045x2vmh4ymau8yvxtmjk7fq83jtky5rlyy2a6f44ucsjwgevq
  - &newton age162v5365xrnzm9tlxy4w3e6fqds7k3h029qezvl73z6rs5skcn9hs7vml45
  - &lisa age1m6efmv7zr9kks4h3w2su74sda5keshghwtw57mzn4sl7kvr7j5sqhs7mdc
  - &tower age1qlwzeg37fwwn2l6fm3quvkn787nn0m89xrjtrhgf9uedtfv2kqlqnec976
  - &lambda age1z5n73rq83mjt6xsmanvgylks5gpmawhqfcz6dtwkc5cu0rlje5js4zzy9s
  - &bin-cache age10d49ptrmad2n7rke6helvmmm86gf06gj9gtfxsh334f3hfr0eewqqa2a7w
  - &core-security age1qedjtr4llnmue2r08ec64mtkl8hpkdsn5mpfh26l3pngmxdm2ymq2tfh80
  - &enigma age109qksyjgdnf7elnk98dh4vtxt0epju7xjemlqng0j0x75st5zg9qm9h3hy
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *macintosh
      - *newton
      - *lisa
      - *tower
      - *lambda 
      - *bin-cache
      - *core-security
      - *enigma
  - key_groups: 
    - age:
      - *macintosh
      - *newton
      - *lisa
      - *tower
      - *lambda
      - *bin-cache
      - *core-security
      - *enigma
