keys:
  - &macintosh age1ac9aek30209ppmxxxpfc65wet344u57pdy3zmk3whjlta38m6q9s9m666g
  - &newton age162v5365xrnzm9tlxy4w3e6fqds7k3h029qezvl73z6rs5skcn9hs7vml45
  - &lisa age1p0r7ja787nmdl4s3wt3sdacg75d7kskmrurgw2ju5n4t0h0jpezsrm25lw
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *macintosh
      - *newton
      - *lisa
  - key_groups: 
    - age:
      - *macintosh
      - *newton
      - *lisa
